### PR TITLE
Bump version to v0.7.0

### PR DESCRIPTION
**Pull request by berendkleinhaneveld**
Bump version to v0.7.0

* Add CI for python 3.11 and 3.12
* Update Pyside dependency to 6.6 to be compatible with python 3.12
* Add support for Pyside 6.6 asyncio
* Updated pygfx to 0.1.17

### CODE REVIEW

**Comment by Korijn** [comment]
You also need to use numpy 1.26 at a minimum for 3.12. I used environment markers to allow for lower versions of numpy for python < 3.12

**Comment by berendkleinhaneveld** [comment]
Think I'll forgo testing on 3.12 now, more trouble than it's worth. 😅

**Comment by Korijn** [comment]
All you have to do is lock again on python 3.12 right?

**Comment by berendkleinhaneveld** [comment]
The test suite might run successful but the example don't yet... Will have to fix that first before merging.

**Pull request merged**
